language: php

git:
  depth: 1

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

  include:
    - php: 5.5
    - php: 5.5
      env: setup=lowest
    - php: 5.6
    - php: 5.6
      env: setup=lowest
    - php: 7.0
    - php: 7.0
      env: setup=lowest
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest
    - php: nightly
    - php: nightly
      env: setup=lowest
    - php: hhvm
    - php: hhvm-nightly
      env: setup=lowest

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

install:
  - phpenv config-rm xdebug.ini || true
  - if [[ $setup != 'lowest'   ]]; then travis_retry composer update -n --no-suggest; fi
  - if [[ $setup  = 'lowest'   ]]; then travis_retry composer update -n --no-suggest --prefer-lowest; fi

script: vendor/bin/phpspec run --format=pretty
